<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.1 setup script
 * Date: Sun, 01 Oct 2023 08:01:37 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: ionos [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'local';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'Kookies7*';

/* End of servers configuration */

$cfg['DefaultLang'] = 'fr';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

